1. Read mobile dataset using pandas, and preprocess it (fill null values).

In [8]:
#1
import numpy as np
import pandas as pd
df=pd.read_csv('C:/Users/vinny/Documents/B.Tech -  CSE/TT - PYTHON\Assignments folder/mobile_cleaned.csv')
df.isnull()
df.fillna(df.mean(),inplace=True)
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(df)

     sim_type   aperture  gpu_rank      weight  stand_by_time  \
0           0   7.694444        55  155.000000     250.000000   
1           0   1.000000        55  132.000000     300.000000   
2           0   9.000000        55  142.000000     329.000000   
3           0   8.000000        55  152.000000     385.000000   
4           1   1.000000        55  234.000000     385.000000   
5           0  14.000000        55  179.000000     280.000000   
6           1   1.000000        56  124.000000     230.000000   
7           0   8.000000        41  154.000000     182.000000   
8           1   8.000000        41  214.000000     182.000000   
9           0   1.000000        55  155.000000     435.000000   
10          0   1.000000        55  169.000000     404.584906   
11          0  10.000000        55  137.000000     300.000000   
12          0   1.000000        50  135.000000     280.000000   
13          0  11.000000        43  133.000000     198.000000   
14          0   8.000000 

2. Draw correlation graph for mobile price with all attributes.

In [ ]:
#2
import matplotlib.pyplot as plt
plt.rcParams.update({'figure.max_open_warning':0})
for col in df.columns:
    if(col!='price'):
        df.plot(x='price',y=col)

3. Compute outer product of 2 vectors.
   Eg:original matrix:[[1, 0], 
                       [0, 1]]
                      [[1, 2], 
                       [3, 4]]
   Outer product of the said two vectors:
   [[1 2 3 4] 
    [0 0 0 0]
    [0 0 0 0]
    [1 2 3 4]]

In [5]:
#3
p=[[1,0],[0,1]]
q=[[1,2],[3,4]]
np.outer(p,q)

array([[1, 2, 3, 4],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 2, 3, 4]])

4.  Write a NumPy program to compute the condition number of a given matrix.
    Original matrix:6.[[1 2]
                       [3 4]]
    Condition number of the said matrix:9.14.9330343737

In [6]:
#4
r=[[1,2],[3,4]]
np.linalg.cond(r)

14.933034373659265

5. write a NumPy program to compute the sum of the diagonal element of a given array(matrix).

In [7]:
#5
s=[[1,2,3],[4,5,6],[7,8,9]]
np.trace(s)

15